# Generated by Django 3.2.7 on 2022-02-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220206_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated']},
        ),
    ]
